config/routes.rb
Rails.application.routes.draw do
  resources :products 
  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  # Make sure price is positive
  monetize :price_cents, numericality: {
    greater_than_or_equal_to: 0
  }

  validates :name,
    presence: {message: "must be present."},
    length: { maximum: 40, message: "cannot be more than 40 characters long." }
    
  validates :description,
    presence: { message: "must be present." },
    length: { maximum: 255, message: "cannot be more than 255 characters long." }
    
  validates :price, presence: { message: "must be present." }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all.order('products.created_at DESC')
  end

  # GET /products/1
  def show
    respond_to do |format|
      format.js
      format.all {render_404}
    end
  end

  # GET /products/new, type JS
  def new
    @product = Product.new
    respond_to do |format|
      format.js
      format.all {render_404}
    end
  end

  # GET /products/1/edit
  def edit
    # Handled in :set_product before_action
  end

  # POST /products, type JS
  def create
    @product = Product.new(product_params)

    respond_to do |format|
    # Handling of result is done in create.js
      @result = @product.save
      if @result
        format.js {redirect_to @product}
      else
        format.js
      end
      format.all {render_404}
    end
  end

  # PATCH/PUT /products/1, type JS
  def update
    respond_to do |format|
      @result = @product.update(product_params)
      if @result
        format.js {redirect_to @product}
      else
        format.js
      end
      format.all {render_404}
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # Called in before_action
  def set_product
    @product = Product.find(params[:id])
  end

  # Strong parameters (Rails 4+)
  def product_params
    params.require(:product).permit(:name, :price, :description)
  end
  
  # Renders a 404 page
  def render_404
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Product Listing Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_products.html.erb
<% @products.each do |product| %>
<%= link_to product_path(product), id:"product-#{product.id}", remote: true do%>
<div class="product-item">
	<%= image_tag 'placeholder.png' %>
	<div class="product-attributes">
		<div class="product-name">
			<%= product.name %>
		</div>
		<div class="price">
			$<%= product.price %>
		</div>
	</div>
</div><!-- Product Item -->
<% end %>
<% end %>

app/views/products/_show.html.erb
<!-- Keep all page content within the page-content inset div! -->
<div class="page-content">

	<div class="col-md-12 product-info">
		<h3><%= @product.name %></h3>
		<div class="product-price">
			$<%= @product.price %>
		</div>
		<div class="product-description well">
			<%= @product.description %>
		</div>
	</div>

	<%= link_to 'Edit', edit_product_path(@product), remote: true, class: "btn" %> 
	<%= link_to 'Delete', product_path(@product), method: 'delete', class: "btn btn-danger",
	data: {confirm: "Are you sure you want to delete this product?"} %>
</div>

app/views/products/create.js.erb
<% if !@result %>
  $('#error').html('<%= j(render :partial => 'shared/modal_errors', :object => @product) %>');
<% end %>

app/views/products/edit.js.erb
// Creates a new modal for editing
$('.modal-content').html("<%= escape_javascript(render 'shared/modal_form') %>");
$('#modal-label').html('Edit Product');
$('#new-modal').modal('show');

app/views/products/index.html.erb
<div id="wrapper">
	<!-- Sidebar -->
	<div id="sidebar-wrapper">
		<div class="jumbotron well">
			Product Listing Application
		</div>
		<%= link_to 'New Product', new_product_path, class: "btn btn-success", remote: true %>
		<div class="product-listing">
			<%= render 'products' %>
		</div>
	</div>
	<!-- Sidebar Wrapper -->

	<!-- Page content -->
	<div id="page-content-wrapper"></div>

</div>
<%= render 'shared/modal'%>

app/views/products/index.js.erb
$('.product-listing').html("<%= escape_javascript(render 'products') %>");

app/views/products/new.js.erb
// Creates modal for new
$('.modal-content').html("<%= escape_javascript(render 'shared/modal_form') %>");
$('#modal-label').html('New Product');
$('#new-modal').modal('show');

app/views/products/show.js.erb
// Close any existing modals (from redirection)
$('#new-modal').modal('hide');
$('#page-content-wrapper').html("<%= escape_javascript(render 'show') %>");

$.ajax({
	type: "GET",
	url: '<%= products_path %>.js'
});

app/views/products/update.js.erb
<% if !@result %>
  $('#error').html('<%= j(render :partial => 'shared/modal_errors', :object => @product) %>');
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="new-modal" tabindex="-1" role="dialog" aria-labelledby="new-modal" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>

app/views/shared/_modal_errors.html.erb
<% if @product.errors.any? %>
<h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>
<ul>
	<% @product.errors.full_messages.each do |message| %>
	<li>
		<%= message %>
	</li>
	<% end %>
</ul> 
<% end %>

app/views/shared/_modal_form.html.erb
<%= form_for(@product, remote: true) do |f| %>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
		&times;
	</button>
	<h4 class="modal-title" id="modal-label"></h4>
</div>
<div class="modal-body">
	<div id="error"></div><!-- Errors in form -->
	<div class="field">
		<%= f.label :name %>
		<br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :price %>
		<br>
		<%= f.number_field :price, :class => 'text_field', :step => 'any'%>
	</div>
	<div class="field">
		<%= f.label :description %>
		<br>
		<%= f.text_area :description %>
	</div>

</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">
		Close
	</button>
	<%= f.submit "Save", class: "btn btn-primary" %>
</div>
<!-- Modal footer -->
<% end %>